---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello
  namespace: pratik
spec:
  chart:
    spec:
      chart: hello-world
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: hello
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: hello
  targetNamespace: hello

