---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pod-release
  namespace: pratik4
spec:
  chart:
    spec:
      chart: pod-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pod
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: pod
  targetNamespace: pod

